config/routes.rb
Rails.application.routes.draw do
  resources :items

  get 'open-items' => 'items#list'

  post 'items/:id/done', to: 'items#done'
  

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :done]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/list
  def list
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def done
    @item.destroy
    @items = Item.all
    respond_to do |format|
      format.html { render :list }    
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :priority, :done, :done_at, :due_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.label :due_at %><br>
    <%= f.datetime_select :due_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div ng-controller='listItems'>

  <table>
    <tbody>
        <tr ng-repeat="item in items">
          <td class='mobile'>{{ item.title }}</td>
          <td><button ng-click="removeItem($index)">Done</button></td>
        </tr>
        <tr>
          <td>
            <input type='text' id='newItem' ng-model='newItem' maxlength='30' class='mobile' />
          </td>
          <td>
            <button ng-click="addItem()" ng-disabled="!newItemValid(newItem)">Add</button>
          </td>
    </tbody>
  </table>

</div>

app/views/items/list.html.erb
<div ng-controller='listItems'
<table class='center'>

  <tbody>
      <tr>
      <tr ng-repeat="item in items">	
        <td class='mobile'><big>{{ item.title }}<big></td>
        <td><%= button_to 'Done', controller: 'items', action: 'done', id: item, class: 'red-button' %></td>
      </tr>
    <% end %>
      <tr><td><form><input type='button' value="Refresh" onClick="window.location.reload()"</form> </td></td></tr>

  </tbody>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @item.priority %>
</p>

<p>
  <strong>Done:</strong>
  <%= @item.done %>
</p>

<p>
  <strong>Done at:</strong>
  <%= @item.done_at %>
</p>

<p>
  <strong>Due at:</strong>
  <%= @item.due_at %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='lists'>
<head>
  <title>Lists</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>  
  <%= javascript_include_tag "itemcontroller" %>  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>